name: R-Type - Project

on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

jobs:
  check_program_compilation_linux:
    name: Build on linux
    runs-on: [ self-hosted, linux, x64 ]
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        run: ./.github/ci_scripts/run_make.sh
  check_program_compilation_windows:
    name: Build on windows
    runs-on: [ self-hosted, windows, x64 ]
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        run: ./.github/ci_scripts/run_make.bat
  code_analyzer:
    name: Code analyzer
    runs-on: [ self-hosted, linux, x64 ]
    needs: check_program_compilation_linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install cppcheck
        run: sudo apt-get update && sudo apt-get install cppcheck -y
      - name: Run cppcheck
        run: ./.github/ci_scripts/run_cppcheck.sh
  run_tests:
    name: Run unit tests
    runs-on: [ self-hosted, linux, x64 ]
    needs: code_analyzer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: run tests
        run: make run_tests




